sudo: false
dist: trusty
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - libasound2-dev
      - libxinerama-dev
      - libgl1-mesa-dev-lts-xenial
language: cpp
before_script:
  - git submodule update --init --recursive
  - git clone https://github.com/Kode/nodejs_bin.git
  - nodejs_bin/copysysbin.sh
script: nodejs_bin/node make.js --kore . --from Tests/Empty --noshaders --compile
