name: Doxygen

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Apt Update
      run: sudo apt-get update
    - name: Apt Install
      run: sudo apt-get install doxygen --yes --quiet
    - name: Create documentation
      run: doxygen Doxyfile
    - name: Clone website
      run: git clone -b gh-pages https://github.com/Kode/Kinc.git Kinc-pages
    - name: Remove old documentation
      run: rm -r Kinc-pages/api
    - name: Copy new documentation
      run: cp -R Docs/html Kinc-pages/api
    - name: Set name
      run: git config --global user.name "Robbot"
    - name: Set email
      run: git config --global user.email "robbot2019@robdangero.us"
    - name: Add documentation
      run: git -C Kinc-pages add .
    - name: Commit documentation
      run: git -C Kinc-pages commit -m "Update documentation to $GITHUB_SHA."
    - name: Push documentation
      run: git -C Kinc-pages push https://Kode-Robbot:$ROBBOT_PASS@github.com/Kode/Kinc.git gh-pages
      env:
        ROBBOT_PASS: ${{ secrets.ROBBOT_PASS }}
